/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mrgame64' at '11/20/16 3:41 PM' with Gradle 2.13
 *
 * @author mrgame64, @date 11/20/16 3:41 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
